### ISSUE TITLE
App Framework: Changes on cluster manager not get pulled from config map

### ISSUE THREAD

**Issue by bendermar** [splunk/splunk-operator#1014]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
When changing the cluster manager yaml and push out to the environment only the config map gets updated. The changes are not visible inside of the pod himself. Seems same behaviour as in the CSPL-1529 bug. 

**Expected behavior**
Changes should get pulled from config map.

**Splunk setup on K8S**
1.24.6

**Reproduction/Testing steps**
Create a cluster manager. Then add a new index for example.

Operator version 2.1.1

**Comment by akondur** [comment]
Hi @bendermar , could you:

1.  Please share the exact steps to reproduce the bug? i.e the exact clusterManager yamls before and after.
2.  Please share what is the expectation i.e what changes do we expect to see on the pod?
3. Are you using the latest way of configuring [appFramework](https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md)?

Looking forward to hearing from you.

**Comment by bendermar** [comment]
Hello Arjun,

we configured for testing purposes some indexes over the clustermanger yaml file. When we will add an index after first push the not will appear in the manage-apps folder only on the config map.
We also implemented APP Framework. Does it mean adding indexes over yaml is not supported? The documentation about all those things is not really good. We also not want to have unencrypted passwords which is the case in both variants.
Over App Framework the password is in cleartext on the S3 .

Here example of a new index that was added after installation.

***@***.***

Mit freundlichen Grüßen

Markus Bender
Monitoring Solutions

Schwarz IT GmbH & Co. KG
Stiftsbergstraße 1 · D-74172 Neckarsulm

Büro: D-74189 Weinsberg · Haller Straße 60

Telefon: +49 (0) 7132 30 455132
***@***.******@***.***>

Kommanditgesellschaft · Sitz: Neckarsulm
Registergericht Stuttgart · HRA 730995

**Comment by akondur** [comment]
Hey @bendermar , while SmartStore can be used to configure indexes on the Indexer Cluster we recommend using AppFramework as the primary mechanism for configuration management with the Splunk Operator as mentioned in the smartstore guide [here](https://github.com/splunk/splunk-operator/blob/main/docs/SmartStore.md#smartstore-resource-guide).

Having said that, upon investigating the issue further with operator version 2.1.1 we have identified a bug in the smartstore implementation where the symbolic links break once the Splunk container starts and it will be fixed in the following [PR](https://github.com/splunk/splunk-operator/pull/1053).

Please feel free to close the issue if you are switching to use appFramework by deprecating the smartstore implementation.

**Comment by akondur** [comment]
Hey @bendermar , raised a [PR](https://github.com/splunk/splunk-operator/pull/1053) to fix this on develop. Issue will be resolved with the next release. Please read the above [comment](https://github.com/splunk/splunk-operator/issues/1014#issuecomment-1420220872) for recommended practices.

**Comment by akondur** [comment]
Hey @bendermar , FYI the [PR](https://github.com/splunk/splunk-operator/pull/1053) has been merged and issue is fixed in develop. Will close out the issue after the next release.

**Comment by akondur** [comment]
Closing with [2.2.1 release](https://github.com/splunk/splunk-operator/releases/tag/2.2.1)
