### ISSUE TITLE
support extraENV in spec

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#184]
Provide a method to specify extra env arguments via the CR
for example

spec:
  extraENV:
     - name: somehting
       value: something

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , currently you could use **defaults**, **defaultsUrl** [common spec parameter](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-splunk-enterprise-resources) to pass in any environment variables which you want ansible to read. Could you share a little bit more on the use case for the extra environment variables?

**Comment by rfaircloth-splunk** [comment]
This would not actually set environ, my use case is to pass env variables into the container to configure options of Splunk addons for example to configure an add-on on deployment to connect to a prod vs a stage api server

**Comment by romain-bellanger** [comment]
Another use case which would be extremely useful for us would be to pass ANSIBLE_EXTRA_FLAGS="-vvv" to enable debug logs. This variable is used in the entry point of the docker image /sbin/entrypoint.sh to pass additional parameters when calling ansible. This would help a lot the investigation, as we needed many times to debug pods not starting because of errors in the ansible playbook.

**Comment by jryb** [comment]
The `extraEnv` parameter has been added to the common CR spec via: https://github.com/splunk/splunk-operator/pull/325
