### ISSUE TITLE
need to update the splunk-ansible version in order to install splunkbase apps

### ISSUE THREAD

**Issue by frajuqeb** [splunk/splunk-operator#345]
We're seeing an error when attempting to install splunkbase apps similar to the one described here:
https://github.com/splunk/splunk-ansible/issues/618
This was fixed & merged:
https://github.com/splunk/splunk-ansible/pull/610
But looking at the inventory/environ.py, it seems the splunk-operator using a version of splunk-ansible that doesn't contain the fix.

**Comment by pogdin** [comment]
I don't believe we would suggest using this method to install Apps on the cluster as the Splunkbase username/password ends up in the yaml file.  Our preferred approach would be to download the Splunkbase app to a local repo where it can be versioned and changed, then once ready for distribution/updated to the Splunk cluster, added to the "apps_location:" stanza.

**Comment by frajuqeb** [comment]
We've created a git repo to hold our helm config to deploy the splunk operator. We'd need to add the apps' tgz files to the repo which will make it bloated. We're very much rather just tell the various servers to install apps x, y, & z from splunkbase using these creds.

**Comment by pogdin** [comment]
The size limitation is likely due to the configmap size constraint (1MB).  In which case we would suggest using the[ URL approach](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#installing-splunk-apps).  Otherwise, it could be an issue with your ingress service not permitting files of a certain size but this is configurable.

I would continue to advocate to not pull Apps directly from Splunkbase.  Perhaps for certain things, like a TA that only resides on Indexers, it could be ok but we've found that Apps that reside there do not have uniform packaging which could affect behavior when they land on the Splunk tier.  Also, any changes you might want to make to the default App would be lost if you had to rebuild the cluster or redeploy the tier.  From our recent [pull requests](https://github.com/splunk/splunk-operator/pull/243), I believe you can see where we are heading with the App Install method beyond Configmaps and URLs.

**Comment by akondur** [comment]
Hey @frajuqeb , could we go ahead and close the issue with the suggestion from @pogdin above to use the app framework? Also there have been multiple [branch releases ](https://github.com/splunk/splunk-ansible/tags) in splunk-ansible which should contain the [fix](https://github.com/splunk/splunk-ansible/pull/610).
