### ISSUE TITLE
Splunk Operator is deleting Smart store secrets

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#569]
When a secret is used for smart store and the cluster is deleted the secret is also deleted. The operator did not create the resource and should not remove it.

**Comment by pogdin** [comment]
What command are you using to delete the services so I can repro?
````
kubectl delete cm-idxc --all
kubectl delete idxc --all
````

**Comment by rfaircloth-splunk** [comment]
kubectl delete -f

**Comment by rfaircloth-splunk** [comment]
I found the repro. I incorrectly configured the CM record to use app-management with an invalid bucket. When the CM enters this state there is a crash loop. Its not possible to "fix" the CM record as the operator won't apply updates when its in a bad state. So I deleted my CM CR however operator will not delete the CR if its in a bad state. So I had to edit the CR to remove the finalizer. which allowed the delete of the CR when the operator lost track of the object it deleted the secret

**Comment by sgontla** [comment]
CR adds the ownership to the Secret object so that the CR can watch for any changes, and act accordingly. If we are deleting the CR without finalizing it, then, I think the garbage collector is cleaning the secret object, as that is the last reference. I think, probably we need to have some incremental logic to fix, in case the current config is bad.

**Comment by sgontla** [comment]
@rfaircloth-splunk , I was able to reproduce this scenario with the `smartstore` config on the CR. As mentioned in my last update, it is the garbage collector which is deleting the secret object.

Smartstore config includes S3 keys, which are configured through the K8 secret object. CR adds the ownership to the secret object, so that, it can watch for any changes with the secret object. When the CR is getting deleted,  as part of handling the finalizers, it also removes its owner reference from the secret object. In case the finalizers are not there, the CR controller doesn't get an opportunity to remove the owner references for the CR under deletion. So, the background garbage collector is deleting the secret object, as that was the last owner referencing the secret object. For a proper clean-up, finalizers are necessary, which helps in handling the pre-delete operations by the Operator(the CR controller).

I know, you were not able to clean up the CM CR, as it was getting stuck with the finalizers. Up to release 1.0.5, as part of the finalizers the Operator is trying to reach the CM to get cluster-info. In your case, the CM itself is not up, so, it was stuck at that step. With the latest code on Develop branch, the finalizers will proceed, if the CM is not reachable. So, this is not going to be an issue anymore.

Hope we can close this ticket, as it is not an issue with the latest code. Please let us know.
