### ISSUE TITLE
Persistent volume gets deleted

### ISSUE THREAD

**Issue by dhanasekar79** [splunk/splunk-operator#593]
Removing the CR for search head and cluster master is removing the persistent volume created for it. Is there a way to retain the persistent volume even after deleting the CR?

Note: I am not using the finalizers for PVC in the custom resource and as per the documentation, it should not remove the pvc. However, in my case, the volumes are removed after removing the chart.

Is that the expected behavior?

We are moving the operator to production and concerned with the  integrity of the Persistent volume created.

**Comment by pogdin** [comment]
Hi, I believe this is expected behavior when deleting the CR entirely

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#delete-a-customresourcedefinition

"When you delete a CustomResourceDefinition, the server will uninstall the RESTful API endpoint and delete all custom objects stored in it."

That includes the PVC.  If you just want to delete the SHC or CM-IDXC from the cluster, do:
````
kubectl delete cm-idxc --all
kubectl delete shc --all
````

**Comment by dhanasekar79** [comment]
ok. Great. Thanks.

**Comment by dhanasekar79** [comment]
.
