### ISSUE TITLE
Allow Indexers to use Master as DeploymentServer

### ISSUE THREAD

**Issue by Caldas** [splunk/splunk-operator#80]
Create a configuration flag at Indexer yaml deployment that will set the cluster master as deployment server and set the deployment client at indexers

**Comment by mikedickey** [comment]
For clustered indexers (which is all operator supports), you should use cluster master instead of deployment server to manage the distribution of apps. As per [docs](https://docs.splunk.com/Documentation/Splunk/8.0.4/Updating/Aboutdeploymentserver):

> The deployment server is the tool for distributing configurations, apps, and content updates to groups of Splunk Enterprise instances. You can use it to distribute updates to most types of Splunk Enterprise components: forwarders, **non-clustered indexers**, and search heads.

For more info, please see my comment in #38 about master-apps and slave-apps.

**Comment by Caldas** [comment]
Thanks @mikedickey
