### ISSUE TITLE
Splunk Operator: DB Connect on a Splunk-operator managed instance

### ISSUE THREAD

**Issue by lxbrd** [splunk/splunk-operator#859]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
We are using the Splunk Operator for Kubernetes for some Standalone Instances. It works so far.  
But now we want to use DB Connect on a Standalone Deployment. 
The installation of DB Connect and the JDBC Drivers work, but we get errors. 
- Cannot communicate with task server, please check your settings. ( Task Server needs a valid JAVA HOME Path)

The errors are related to the missing JRE on the docker image. 
How are we supposed to use db connect without JRE in the Splunk-Standalone pod?

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Splunk setup on K8S**
Kubernetes Cluster with Splunk-Operator and a Splunk Standalone deployment.

**Reproduction/Testing steps**
- Setup a new Cluster
- Install splunk-operator
- install splunk-standalone
- port forward standalone
- install db-connect via Web-UI / Or download and install from file

**Proposed changes(optional)**
- Provide a way to use DB-Connect (eg. install java)

**Comment by pogdin** [comment]
@lxbrd , thanks for filing.  We are aware and currently working on releasing a Splunk Enterprise Docker container with Java installed to support this and other use cases.

**Comment by adamrushuk** [comment]
I've not tested this on the latest v9 containers, but was able to enable java by adding this env var to our Splunk helm chart:
```yaml
env:
- name: JAVA_VERSION
    value: openjdk:8
```

The Java version then shows within the running container:
```
[ansible@forwarder-0 splunk]$ java -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
```

The above code works for `splunk/splunk:8.2`.

**Comment by mittelangelo** [comment]
@pogdin @adamrushuk First, thank you for your comments!
I tried to add the env in the standalone deployment since I don't use Helm, but sadly, I could not make it work. 
So, I tried [extraEnv](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-all-resources) `spec: extraEnv: -name: JAVA_VERSION value: openjdk:8` and [defaults](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-splunk-enterprise-resources) `spec: defaults: | 'JAVA_VERSION: openjdk:8'`, but that also did not work (with lower- and uppercase Java-version). 
Currently, I am looking at creating a configmap with [this](https://github.com/splunk/splunk-ansible/blob/2b6e92b7409d7791fe4717fff8cf25690b56f01f/docs/advanced/default.yml.spec.md?plain=1#L122) value to override the defaults.yml: 
```
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: example
  namespace: splunk-operator
spec:
  volumes:
    - name: defaults
      configMap:
        name: java-enabled
  defaultsUrl: /mnt/defaults/default.yml

```
But I am not very optimistic to make it work. I think I don't understand Ansible and the operator itself enough.
I will keep you updated if I make progress.

**Comment by adamrushuk** [comment]
@mittelangelo I just tried using `JAVA_VERSION: openjdk:8` extraEnv and saw this in the logs: `WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml`. Looks like maybe the `extraEnv` method doesn't merge, so you'll have to override _all_ required env vars.

At least I can see `JAVA_VERSION` is the correct var to use looking at the ansible spec: https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md

Please let me know if you find a working solution.

**Comment by mittelangelo** [comment]
@adamrushuk I get a different Error: 
```
fatal: [localhost]: FAILED!
"changed": false,
"rc":
1
MSG:
MODULE FAILURE
See stdout/stderr for the exact error
MODULE STDERR:
sudo: a password is required
```
Maybe I have to take a look at a Splunk installation without admin.
https://github.com/splunk/splunk-operator/blob/develop/docs/Install.md#admin-installation-for-all-namespaces

**Comment by kylcami** [comment]
@pogdin  What are the timelines of having a Splunk image with Java available?

What are the workaround methods without resorting to building a custom image? 
I tried several to no avail. Using the startup user as "root" in attempt to install Java inside the container (splunk.user), failed - still running as "splunk".
Looked up for sudo password, failed.

**Comment by pogdin** [comment]
Please try https://hub.docker.com/layers/splunk/splunk/9.0.1-openjdk11/images/sha256-c3c608300b6291c37515b4d94aa188e287e75f7da0c48572cc8e8bb84b0e6a3f?context=repo
