### ISSUE TITLE
How to implement the App Framework in GCP?

### ISSUE THREAD

**Issue by vishnugit24** [splunk/splunk-operator#861]
### Please select the type of request

Enhancement

### Tell us more

I know that App framework currently doesn't support in GCP. But how can I implement the app framework in GCP? In docs I saw that we can use MINIO for GCP. 
Do we need to install MINIO in a POD?
How to configure the MINIO in GCP?
Is there any YAML code available to setup MINIO?

Could you please help me to setup MINIO in GCP for App framework?

**Comment by jryb** [comment]
There is no need to install minio anywhere.  Since GCS is s3 compliant, the `provider: minio` can be used as part of the 
 app framework config to talk to a generic s3 storage such as GCS.  This PR gives an example on how this is done for GCS using keys: https://github.com/splunk/splunk-operator/pull/498.

**Comment by vishnugit24** [comment]
Thank you very much @jryb 

My app framework is working fine in GCP.
